### ISSUE TITLE
Milestone: execution and infrastructure production launch

### ISSUE THREAD

**Issue by alexveden** [TMQR/SG#32]
The goal of this milestone is to create and debug execution infrastructure to make sure that we are ready for the production execution.

- [ ] Implement and debug TT FIX excution

- [ ] Implement low-level diagnostic tools

- [ ] Implement infrastructure dashboard (private monitoring)

- [ ] Implement campaign reporting (public monitoring / reporting)
